### ISSUE TITLE
Name tweaks/aliases

### ISSUE THREAD

**Issue by chocolateboy** [landau/predicate#3]
Some of the names are a bit ugly/inconsistent IMO (e.g. `rgx`/`RegExp`). For the relational predicates, there's lots of [prior art](https://en.wikipedia.org/wiki/Relational_operator#Standard_relational_operators) for the following (complementing the current `eq`, `lt` and `gt`):

* le (<=)
* ge (>=)

I'd also prefer `regex` and/or `regexp` instead of `rgx` (which I don't think I've ever seen anyone use before) or `RegExp` (why camel case? why ucfirst?).

Happy to create a pull request if interested.

**Comment by chocolateboy** [comment]
Another suggestion: `nan` as an alias for `NaN`, again to preserve consistent (lower) casing.

**Comment by landau** [comment]
Nice. I do like `le` and `ge` better.

**Comment by landau** [comment]
I've added these alias'. I'll deprecate some of the older alias later. cheers. btw, no need to ask for permission to make a PR. feel free to PR anytime. additionally `RegExp` casing is called Pascal Case. :)
