### ISSUE TITLE
Docs don't display correctly in Firefox

### ISSUE THREAD

**Issue by chocolateboy** [landau/predicate#4]
[This](https://i.imgur.com/BzF2wP7.png) is what I see in Firefox 34.0 with a clean profile on Ubuntu 14.04. Disabling the CSS with `View` -> `Page Style` -> `No Style` "fixes" the problem (i.e. the page is at least readable, though not -- of course -- formatted as intended).

[The page](http://landau.github.io/predicate/) displays fine in Chromium.

**Comment by landau** [comment]
Ouch. My laziness has only tested the docs on chrome. I'll look into this. Thanks!

**Comment by chocolateboy** [comment]
Looks fine now (Firefox 50.0, Linux (Arch)).
