### ISSUE TITLE
Add match predicate?

### ISSUE THREAD

**Issue by chocolateboy** [landau/predicate#5]
Or `predicate.matches` or `predicate.like`. Takes a regex and returns true if the supplied value matches.

See [here](https://github.com/lodash/lodash/issues/971) for an example.

**Comment by landau** [comment]
Are you saying that `predicate.matches(/foo/, 'foo') === /foo/.test('foo');`? I can see from your example that you'd like the power of currying.

This does seem like a nice function to add. I'll do it.

Did you see jdalton's response about `bind`?

`_.parition(process.argv.slice(2), RegExp.prototype.test, /^-/);` is certainly a nice solution. I sometimes do this same thing with `filter/every/some`. `[1,2,'a'].filter(RegExp.prototype.test, /\d/); // [1,2]`

**Comment by landau** [comment]
@chocolateboy Thoughts?

**Comment by chocolateboy** [comment]
> Are you saying that predicate.matches(/foo/, 'foo') === /foo/.test('foo');?

I ended up using [this](https://github.com/wookieb/predicates/blob/master/docs/api.md#matches), so I guess that's the API I had in mind.

> Did you see jdalton's response about bind?

Yes. I found it unsatisfying. As mentioned, regexps are currently useless as predicates and making them useful has been [requested before](https://github.com/lodash/lodash/issues/672) and will be requested again.

**Comment by landau** [comment]
lol okay. I also like the idea. I can probably get this in today.

**Comment by landau** [comment]
Sorry this took so long. I got very busy at work and lazy at home! lol

**Comment by landau** [comment]
http://landau.github.io/predicate/#matches

**Comment by chocolateboy** [comment]
> [add #matches](https://github.com/landau/predicate/commit/5b0553a0275a866e9a1c10a997d719359a3cba11)

:+1: 

> [add docs for #matches](http://landau.github.io/predicate/#matches)

[:-/](https://github.com/landau/predicate/issues/4)

**Comment by landau** [comment]
Feel free to fix #4 :)
