### ISSUE TITLE
operators "or" and "and"

### ISSUE THREAD

**Issue by lybo** [landau/predicate#9]
Regarding this article https://codepen.io/Universalist/post/predicates-in-javascript
You can include **or** and **and** predicates with multiple args

```js
    function or(...args) {
        return function(x) {
            return args.some(fn => fn(x));
        }
    }

    function and(...args) {
        return function(x) {
            return args.every(fn => fn(x));
        }
    }
```

**Comment by landau** [comment]
Good idea! Implemented. 

https://landau.github.io/predicate/#and
https://landau.github.io/predicate/#or

Released in version `1.1.0`. Use version `1.1.1` for a perf fix in chaining.

 Thanks!
